export const FETCH_REQUESTED = "details/FETCH_REQUESTED";
export const FETCH_REQUESTED_SUCCEEDED = "details/FETCH_REQUESTED_SUCCEEDED";
export const FETCH_REQUESTED_FAILED = "details/FETCH_REQUESTED_FAILED";

export const CLOSE_PROJECT_INFO = "details/CLOSE_PROJECT_INFO";

export const DATA_BASE_DELETE_REQUESTED = "details/DATA_BASE_DELETE_REQUESTED";
export const DATA_BASE_DELETE_REQUESTED_SUCCEEDED =
  "details/DATA_BASE_DELETE_REQUESTED_SUCCEEDED";
export const DATA_BASE_DELETE_REQUESTED_FAILED =
  "details/DATA_BASE_DELETE_REQUESTED_FAILED";

export const PROJECT_DELETE_REQUESTED = "details/PROJECT_DELETE_REQUESTED";
