export const FETCH_REQUESTED = "projects/FETCH_REQUESTED";
export const FETCH_REQUESTED_SUCCEEDED = "projects/FETCH_REQUESTED_SUCCEEDED";
export const FETCH_REQUESTED_FAILED = "projects/FETCH_REQUESTED_FAILED";
export const INFO_FETCH_REQUESTED = "details/FETCH_REQUESTED";
